### ISSUE TITLE
incorrect instructions in README.md

### ISSUE THREAD

**Issue by pixelzoom** [matomo-org/github-sync#5]
Instructions in the README.md are:

```
git clone https://github.com/piwik/github-sync
cd github-sync
composer install
```

There is no `composer` file in the github-sync directory. So on Mac OS with bash, `composer install` fails with error:

> -bash: composer: command not found

**Comment by pixelzoom** [comment]
Additional instructions that fail:

```
Simply run the github-sync.php script to see how to use the command:

./github-sync.php help sync
```

On Mac OS 10.10.3 with bash 3.2.57, this yields:

```
% cd /tmp/github-sync
% ./github-sync.php help sync

Warning: require_once(/tmp/github-sync/vendor/autoload.php): failed to open stream: No such file or directory in /tmp/github-sync/github-sync.php on line 7

Fatal error: require_once(): Failed opening required '/tmp/github-sync/vendor/autoload.php' (include_path='.:') in /tmp/github-sync/github-sync.php on line 7
```

**Comment by mnapoli** [comment]
Hi thanks for the report

The second error is because you didn't run composer. Composer is a PHP tool (like npm, bower, etc), I can see that this command is cryptic for those not familiar with it.

I'll edit the readme, if you want to install it here are the instructions: https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

**Comment by pixelzoom** [comment]
Thanks!
